response = [
    {
        "scientific_name": "Passer domesticus",
        "common_name": "Haussperling",
        "species_code": "houspa",
        "count": 665,
        "hourly_counts": [
            0,
            0,
            0,
            0,
            0,
            7,
            5,
            78,
            102,
            11,
            32,
            25,
            87,
            137,
            96,
            5,
            0,
            39,
            28,
            13,
            0,
            0,
            0,
            0,
        ],
        "high_confidence": True,
        "max_confidence": 0.97,
        "first_heard": "19: 56: 21",
        "latest_heard": "19: 56: 21",
        "thumbnail_url": "/api/v2/media/image/Passer%20domesticus",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
    {
        "scientific_name": "Turdus merula",
        "common_name": "Amsel",
        "species_code": "eurbla",
        "count": 352,
        "hourly_counts": [
            0,
            0,
            0,
            0,
            102,
            61,
            91,
            15,
            14,
            3,
            6,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            38,
            21,
            0,
            0,
            0,
        ],
        "high_confidence": True,
        "max_confidence": 0.97,
        "first_heard": "20: 50: 45",
        "latest_heard": "20: 50: 45",
        "thumbnail_url": "/api/v2/media/image/Turdus%20merula",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
    {
        "scientific_name": "Tettigonia viridissima",
        "common_name": "Grünes Heupferd",
        "count": 146,
        "hourly_counts": [
            108,
            38,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ],
        "high_confidence": True,
        "max_confidence": 0.89,
        "first_heard": "01: 53: 11",
        "latest_heard": "01: 53: 11",
        "thumbnail_url": "/ui/assets/bird-placeholder.svg",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
    {
        "scientific_name": "Cyanistes caeruleus",
        "common_name": "Blaumeise",
        "species_code": "blutit",
        "count": 141,
        "hourly_counts": [
            0,
            0,
            0,
            0,
            0,
            6,
            0,
            15,
            2,
            0,
            0,
            0,
            26,
            17,
            10,
            2,
            0,
            7,
            15,
            41,
            0,
            0,
            0,
            0,
        ],
        "high_confidence": True,
        "max_confidence": 0.94,
        "first_heard": "19: 49: 33",
        "latest_heard": "19: 49: 33",
        "thumbnail_url": "/api/v2/media/image/Cyanistes%20caeruleus",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
    {
        "scientific_name": "Sylvia atricapilla",
        "common_name": "Mönchsgrasmücke",
        "species_code": "blackc1",
        "count": 101,
        "hourly_counts": [
            0,
            0,
            0,
            0,
            1,
            32,
            17,
            4,
            17,
            5,
            4,
            1,
            1,
            4,
            3,
            0,
            0,
            0,
            6,
            6,
            0,
            0,
            0,
            0,
        ],
        "high_confidence": True,
        "max_confidence": 0.95,
        "first_heard": "19: 54: 43",
        "latest_heard": "19: 54: 43",
        "thumbnail_url": "/api/v2/media/image/Sylvia%20atricapilla",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
    {
        "scientific_name": "Pica pica",
        "common_name": "Elster",
        "species_code": "eurmag1",
        "count": 92,
        "hourly_counts": [
            0,
            0,
            0,
            0,
            0,
            3,
            1,
            26,
            3,
            0,
            4,
            3,
            4,
            1,
            2,
            0,
            5,
            9,
            29,
            2,
            0,
            0,
            0,
            0,
        ],
        "high_confidence": True,
        "max_confidence": 0.94,
        "first_heard": "19: 13: 21",
        "latest_heard": "19: 13: 21",
        "thumbnail_url": "/api/v2/media/image/Pica%20pica",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
    {
        "scientific_name": "Poecile palustris",
        "common_name": "Sumpfmeise",
        "species_code": "martit2",
        "count": 7,
        "hourly_counts": [
            0,
            0,
            0,
            0,
            0,
            0,
            5,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            2,
            0,
            0,
            0,
            0,
            0,
        ],
        "high_confidence": True,
        "max_confidence": 0.91,
        "first_heard": "18: 13: 45",
        "latest_heard": "18: 13: 45",
        "thumbnail_url": "/api/v2/media/image/Poecile%20palustris",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
    {
        "scientific_name": "Carduelis carduelis",
        "common_name": "Stieglitz",
        "species_code": "eurgol",
        "count": 4,
        "hourly_counts": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
        ],
        "high_confidence": True,
        "max_confidence": 0.91,
        "first_heard": "19: 30: 14",
        "latest_heard": "19: 30: 14",
        "thumbnail_url": "/api/v2/media/image/Carduelis%20carduelis",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
    {
        "scientific_name": "Fringilla coelebs",
        "common_name": "Buchfink",
        "species_code": "comcha",
        "count": 3,
        "hourly_counts": [
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            2,
            0,
            0,
            0,
            0,
            0,
        ],
        "high_confidence": True,
        "max_confidence": 0.9,
        "first_heard": "18: 26: 13",
        "latest_heard": "18: 26: 13",
        "thumbnail_url": "/api/v2/media/image/Fringilla%20coelebs",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
    {
        "scientific_name": "Parus major",
        "common_name": "Kohlmeise",
        "species_code": "gretit1",
        "count": 3,
        "hourly_counts": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            2,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
        ],
        "high_confidence": True,
        "max_confidence": 0.9,
        "first_heard": "18: 07: 33",
        "latest_heard": "18: 07: 33",
        "thumbnail_url": "/api/v2/media/image/Parus%20major",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
    {
        "scientific_name": "Chloris chloris",
        "common_name": "Grünfink",
        "species_code": "eurgre1",
        "count": 2,
        "hourly_counts": [
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
        ],
        "high_confidence": True,
        "max_confidence": 0.96,
        "first_heard": "17: 46: 51",
        "latest_heard": "17: 46: 51",
        "thumbnail_url": "/api/v2/media/image/Chloris%20chloris",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
    {
        "scientific_name": "Hirundo rustica",
        "common_name": "Rauchschwalbe",
        "species_code": "barswa",
        "count": 1,
        "hourly_counts": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
        ],
        "high_confidence": True,
        "max_confidence": 0.93,
        "first_heard": "18: 24: 01",
        "latest_heard": "18: 24: 01",
        "thumbnail_url": "/api/v2/media/image/Hirundo%20rustica",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
    {
        "scientific_name": "Passer montanus",
        "common_name": "Feldsperling",
        "species_code": "eutspa",
        "count": 1,
        "hourly_counts": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ],
        "high_confidence": False,
        "max_confidence": 0.77,
        "first_heard": "14: 42: 16",
        "latest_heard": "14: 42: 16",
        "thumbnail_url": "/api/v2/media/image/Passer%20montanus",
        "is_new_species": True,
        "days_since_first_seen": 1,
        "is_new_this_year": True,
        "is_new_this_season": True,
        "days_this_year": 1,
        "days_this_season": 1,
        "current_season": "summer",
    },
]
